name: updater
description: Updater Application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  win32: ^2.7.0
  ffi: ^2.0.1
  win32_registry: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
